CREATE TABLE PRODUCT (
ID NUMBER,
CONSTRAINT PRODUCT_PK PRIMARY KEY (ID),
NAME VARCHAR(50) ,
DESCRIPTION VARCHAR(50),
PRICE NUMBER
);
CREATE SEQUENCE PRODUCT_SEQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 2;


