CREATE TABLE ORDER_ (
ID NUMBER,
CONSTRAINT ORDER_PK PRIMARY KEY (ID),
USER_ID NUMBER,
CONSTRAINT  USER_FK FOREIGN KEY (USER_ID) REFERENCES USER_(ID),
ROOM_ID,
CONSTRAINT  ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
DATEFROM DATE,
DATETO DATE,
MONEYPAID DATE
)
