CREATE TABLE USER_ (
ID NUMBER,
CONSTRAINT USER_PK PRIMARY KEY (ID),
USERNAME    VARCHAR(50),
PASSWORD VARCHAR(50),
COUNTRY    VARCHAR(50),
USERTYPE VARCHAR(50),
STREET  VARCHAR(50)
);

CREATE SEQUENCE USER__SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 2;