CREATE TABLE ROOM (
ID NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY (ID),
NUMBEROFGUESTS      NUMBER,
PRICE               NUMBER,
BREAKFASTINCLUDED   NUMBER,
PETSALLOWED         NUMBER,
DATEAVAILABLEFROM   DATE,
HOTEL_ID NUMBER,
CONSTRAINT  HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(ID)

);
CREATE SEQUENCE ROOM_SEQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 2;