CREATE TABLE ROOM (
ROOM_ID NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY (ROOM_ID),
NUMBEROfGUESTS      NUMBER,
PRICE               NUMBER,
BREAKFASTINCLUDED   NUMBER,       ;// (1 или 0)
PETSAllOWED         NUMBER,           ;// (1 или 0)
DATEAVAILABLEFROM   DATE,
HOTELID NUMBER,
CONSTRAINT  HOTEL_FK FOREIGN KEY (HOTELID) REFERENCES HOTEL(ID)
);
CREATE SEQUENCE ROOM_SEQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 2;